global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'snmpsim-api'
    static_configs:
      - targets: ['api:9090']

  - job_name: 'snmpsim-simulator'
    metrics_path: /metrics
    static_configs:
      - targets: ['snmpsim:8080']
